lostpets/lostpets/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", lambda request: redirect("lostpets_web:home")),
    path("admin/", admin.site.urls),
    path("", include("lostpets_web.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

lostpets/lostpets_web/urls.py
from django.urls import path
from django.contrib import admin
from lostpets_web.views import (
    home,
    about,
    login_view,
    register_view,
    pets,
    post,
    logout_view,
    pet_detail,
    pet_update,
    profile_edit,
    pet_update,
    pet_delete,
)
from django.contrib.auth import views as auth_views

app_name = "lostpets_web"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", home, name="home"),
    path("about/", about, name="about"),
    path("pets/", pets, name="pets"),
    path("pets/<int:pk>/", pet_detail, name="petdetail"),
    path("post/", post, name="post"),
    path("pets/<int:pk>/delete/", pet_delete, name="pet_delete"),
    path("post/<int:pk>/edit/", pet_update, name="pet_update"),
    path("login/", login_view, name="login"),
    path("register/", register_view, name="register"),
    path("logout/", logout_view, name="logout"),
    path("profile/", profile_edit, name="profile"),
]

lostpets/lostpets_web/models.py
from django.db import models
from django.contrib.auth.models import User


# Sección Pet
class Pet(models.Model):
    name = models.CharField(max_length=255)
    race = models.CharField(max_length=1500)
    content = models.TextField()
    image = models.ImageField(upload_to="media")
    published_date = models.DateTimeField(auto_now_add=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


# End --> Sección Paginas


# Sección Usuarios
# class UserProfile(models.Model):
#     user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
#     # Agrega campos adicionales si es necesario para tu aplicación

#     def __str__(self):
#         return self.user.username


class Avatar(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="avatar", null=True, blank=True)

    def __str__(self):
        return f"{self.user}"


# End --> Sección Usuarios

lostpets/lostpets_web/forms.py
# lostpets_web/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Pet


## Seccion Usuario
class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(
        label="Nombre de Usuario",
        widget=forms.TextInput(attrs={"class": "form-control my-3 ms-2"}),
        max_length=30,
        required=True,
    )
    email = forms.EmailField(
        label="Correo Electrónico",
        widget=forms.EmailInput(attrs={"class": "form-control my-3 ms-2"}),
        max_length=254,
        required=True,
    )
    password1 = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={"class": "form-control my-3 ms-2"}),
        required=True,
    )
    password2 = forms.CharField(
        label="Confirmar Contraseña",
        widget=forms.PasswordInput(attrs={"class": "form-control my-3 ms-2"}),
        required=True,
    )
    last_name = forms.CharField(
        label="Apellido",
        widget=forms.TextInput(attrs={"class": "form-control my-3 ms-2"}),
        max_length=30,
        required=True,
    )
    first_name = forms.CharField(
        label="Nombre",
        widget=forms.TextInput(attrs={"class": "form-control my-3 ms-2"}),
        max_length=30,
        required=True,
    )

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        ]


## Seccion Pets


class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ["name", "race", "content", "image"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control my-3 ms-2"}),
            "race": forms.TextInput(attrs={"class": "form-control my-3 ms-2"}),
            "content": forms.Textarea(
                attrs={"class": "form-control my-3 ms-2", "rows": 4}
            ),
            "image": forms.ClearableFileInput(
                attrs={"class": "form-control my-3 ms-2"}
            ),
        }
        labels = {
            "name": "Nombre",
            "race": "Raza",
            "content": "Descripción",
            "image": "Imagen",
        }


class AvatarFormulario(forms.Form):
    image = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={"class": "form-control  my-3 ms-2"})
    )


class UserEditForm(forms.Form):
    email = forms.EmailField(
        label="Ingresar email",
        widget=forms.EmailInput(attrs={"class": "form-control  my-3 ms-2"}),
    )
    password1 = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={"class": "form-control  my-3 ms-2"}),
    )
    password2 = forms.CharField(
        label="Repetir Contraseña",
        widget=forms.PasswordInput(attrs={"class": "form-control  my-3 ms-2"}),
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control  my-3 ms-2"})
    )
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control  my-3 ms-2"})
    )

    class Meta:
        model = User
        fields = ["email", "password1", "password2", "last_name", "first_name"]

lostpets/lostpets_web/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from lostpets_web.models import Pet, Avatar
from lostpets_web.forms import (
    PetForm,
    UserRegistrationForm,
    AvatarFormulario,
    UserEditForm,
)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden


def home(request):
    if request.method == "POST":
        formulario = AvatarFormulario(request.POST, request.FILES)

        if formulario.is_valid():
            user = request.user

            # Eliminar el avatar anterior si existe
            avatar = Avatar.objects.filter(user=user).first()
            if avatar:
                avatar.delete()

            # Crear un nuevo avatar
            avatar = Avatar.objects.create(
                user=user, image=formulario.cleaned_data.get("image")
            )

            # Guardar la URL del avatar en la sesión
            if avatar.image:
                request.session["avatar_url"] = avatar.image.url

            return redirect("lostpets_web:home")

    formulario = AvatarFormulario()
    return render(request, "home.html", {"form": formulario})


def about(request):
    return render(request, "about.html")


def login_view(request):
    if request.user.is_authenticated:
        return redirect("lostpets_web:home")

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)  # Aquí usamos la función login importada
                return redirect("lostpets_web:home")
    else:
        form = CustomAuthenticationForm()

    return render(request, "login.html", {"form": form})


def register_view(request):
    if request.user.is_authenticated:
        return redirect("lostpets_web:home")

    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            # Autenticar al usuario después del registro
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)

                # # Set URL Avatar to Sessión
                # avatar = Avatar.objects.get_or_create(user=user)[0]

                # if avatar.image:
                #     request.session["avatar_url"] = avatar.image.url

                return redirect("lostpets_web:home")
        else:
            messages.error(request, "Datos incorrectos")

    else:
        form = UserRegistrationForm()

    return render(request, "register.html", {"form": form})


def logout_view(request):
    logout(request)
    return redirect("lostpets_web:home")


def pets(request):
    pets = Pet.objects.all()
    return render(request, "pets.html", {"pets": pets})


def pet_detail(request, pk):
    pet = get_object_or_404(Pet, pk=pk)
    return render(request, "petdetail.html", {"pet": pet})


@login_required
def post(request):
    if request.method == "POST":
        form = PetForm(request.POST, request.FILES)
        if form.is_valid():
            page = form.save(commit=False)
            page.owner = request.user
            page.save()
            return redirect("lostpets_web:pets")
    else:
        form = PetForm()
    return render(request, "post.html", {"form": form})


@login_required
def pet_update(request, pk):
    # Obtén la mascota por su pk
    pet = get_object_or_404(Pet, pk=pk)

    # Permitir el acceso solo si el usuario es el propietario o un superusuario
    if request.user != pet.owner and not request.user.is_superuser:
        return HttpResponseForbidden("No tienes permisos para editar esta mascota.")

    if request.method == "POST":
        form = PetForm(request.POST, request.FILES, instance=pet)
        if form.is_valid():
            form.save()
            return redirect("lostpets_web:pets")
    else:
        form = PetForm(instance=pet)

    return render(request, "post.html", {"form": form})


@login_required
def profile_edit(request):
    usuario = request.user

    if request.method == "POST":
        formulario = UserEditForm(request.POST)
        print(f"editar_perfil -- POST")
        if formulario.is_valid():
            informacion = formulario.cleaned_data

            print(f"email: {informacion.get("email")}")
            usuario.email = informacion.get("email")
            print(f"last_name: {informacion.get("last_name")}")
            usuario.last_name = informacion.get("last_name")
            print(f"first_name: {informacion.get("first_name")}")
            usuario.first_name = informacion.get("first_name")

            print(f"password1: {informacion.get("password1")}")

            usuario.save()

            return redirect("lostpets_web:home")

    print(f"editar_perfil -- GET")
    formulario = UserEditForm(
        initial={
            "first_name": usuario.first_name,
            "last_name": usuario.last_name,
            "email": usuario.email,
        }
    )

    # Se quitan las Passwords para que no se cambien
    # formulario.fields.pop('password1', None)
    # formulario.fields.pop('password2', None)

    return render(request, "profile_edit.html", {"form": formulario})


@login_required
def pet_delete(request, pk):
    print(request, pk)
    pet = get_object_or_404(Pet, pk=pk, owner=request.user)
    if request.method == "POST":
        pet.delete()
        return redirect("lostpets_web:home")
    return render(request, "pets.html", {"pet": pet})


from django.contrib.auth.forms import AuthenticationForm
from django import forms


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control my-3 ms-2"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control my-3 ms-2"})
    )

lostpets/lostpets_web/templates/about.html
{% extends 'base.html' %}

{% block title %}
LOST PETS - Acerca
{% endblock %}

{% block content %}
<div class="text-center my-5">
    <h1>Acerca de <span class="text-decoration-underline">LOST PETS</span></h1>
    <p>Bienvenidos a <strong>Lost Pets</strong>, un blog dedicado a la búsqueda de mascotas perdidas. Este proyecto ha
        sido desarrollado en Python con el framework Django.</p>
    <p>Este es el proyecto final del curso de Python y Django.</p>
    <br> <br>
    <h3>Acerca del Autor</h3>
    <br>
    <img src="https://media.licdn.com/dms/image/v2/D4D03AQHX5sp0bVdWOA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1719024837114?e=1743638400&v=beta&t=JJc53pL28nEgRQ6eqnoLQZDxNTS06qXstQKu32KYibQ"
        alt="Eduar Chilon" class="rounded-circle" style="width: 250px; height: 250px; object-fit: cover;">
    <br>
    <br>
    <p>Me llamo <strong>Eduar Chilon</strong>, soy de Buenos Aires, Argentina. Me apasiona el desarrollo de software y
        aprender nuevas tecnologías.</p>
</div>


{% endblock %}

lostpets/lostpets_web/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Python/DJango {% endblock %}</title>
    <link rel="icon"
        href="https://www.shutterstock.com/shutterstock/photos/349578821/display_1500/stock-vector-dog-paw-sign-icon-pets-symbol-349578821.jpg"
        type="image/x-icon" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
</head>

<body class="d-flex flex-column" style="min-height: 100vh">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container">
            <a class="navbar-brand text-decoration-underline" href="{% url 'lostpets_web:home' %}"><strong>LOST
                    PETS</strong></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01"
                aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'lostpets_web:home' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'lostpets_web:about' %}">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'lostpets_web:pets' %}">Pets</a></li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'lostpets_web:post' %}">Posts</a></li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav d-flex gap-3">
                    {% if request.user.is_authenticated %}
                    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle d-flex align-items-center" href="#"
                                    id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                    <span class="fw-bold text-capitalize me-3">{{ user.username }}</span>
                                    {% if avatar_url %}
                                    <img src="{{ avatar_url }}" alt="Imagen de perfil" width="40" height="40"
                                        class="rounded-circle" style="object-fit: cover;">
                                    {% else %}
                                    <img src="https://static.vecteezy.com/system/resources/previews/021/334/027/large_2x/smiling-bernese-mountain-dog-avatar-tongue-hanging-out-cute-cartoon-pet-domestic-animal-vector.jpg"
                                        width="40" height="40" class="rounded-circle">
                                    {% endif %}
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="{% url 'lostpets_web:profile' %}">Editar Perfil</a>
                                    <a class="dropdown-item" style="cursor: pointer;" data-bs-toggle="modal"
                                        data-bs-target="#avatarEditModal">Cambiar imágen</a>
                                    <a class="dropdown-item" href="{% url 'lostpets_web:logout' %}">Cerrar
                                        Sesión</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                    {% else %}
                    <li class="nav-item">
                        <a class="btn btn-primary text-white" href="{% url 'lostpets_web:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-warning text-white" href="{% url 'lostpets_web:register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% if request.user.is_authenticated %}
    <!-- Modal -->
    <div class="modal fade" id="avatarEditModal" tabindex="-1" aria-labelledby="avatarEditModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="avatarEditModal">Cambiar imágen de perfil</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST" enctype="multipart/form-data" class="col-md-12" id="form-avatar">
                        {% csrf_token %}
                        <div class="mb-3" for="id_image">
                            {{ form_avatar.image }}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                            <button type="submit" class="btn btn-primary" form="form-avatar">Guardar cambios</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}


    <div id="carouselExampleCaptions" class="carousel slide">
        <div class="carousel-inner">
            <div class="carousel-item active d-flex align-items-center justify-content-center"
                style="height: 350px; background-color: #1a1616;">
                <img src="https://i0.wp.com/erikaapellaniz.com/wp-content/uploads/2021/06/Animales-Extraviados.jpg?resize=800%2C420&ssl=1"
                    class="d-block w-100 h-100 object-fit-cover" alt="fondo" style="opacity: 0.7;" />
                <div class="carousel-caption d-flex flex-column align-items-center justify-content-center h-100">
                    <h1 class="fw-bold text-decoration-underline" style="font-size: 65px;">LOST PETS</h1>
                    <h3>Entre todos podemos ayudarnos a encontrar a ese miembro de la familia que nos
                        hace mucha falta
                    </h3>
                    {% if request.resolver_match.url_name != 'pets' %}
                    <a class="btn btn-warning fw-bold mt-3 px-4 py-2" href="{% url 'lostpets_web:pets' %}">
                        Ver todas las mascotas
                    </a>
                    {% else %}
                    <a class="btn btn-warning fw-bold mt-3 px-4 py-2" href="{% url 'lostpets_web:post' %}">
                        Publicar mascotas perdidas
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <main class="container" style="flex-grow: 1">
        {% block content %} {% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <div class="container-fluid">
        <footer class="border-top">
            <div class="container d-flex flex-wrap justify-content-between align-items-center py-3 my-4">
                <p class="col-md-4 mb-0 text-body-secondary">
                    © 2025 Eduar Chilon Cruz
                </p>

                <a href="/"
                    class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                    <svg class="bi me-2" width="40" height="32">
                        <use xlink:href="#bootstrap"></use>
                    </svg>
                </a>

                <ul class="nav col-md-4 justify-content-end">
                    {% if request.user.is_authenticated and request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link px-2 text-body-secondary" href="/admin/">Admin</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link px-2 text-body-secondary" href="{% url 'lostpets_web:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-2 text-body-secondary" href="{% url 'lostpets_web:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-2 text-body-secondary" href="{% url 'lostpets_web:pets' %}">Pets</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link px-2 text-body-secondary" href="{% url 'lostpets_web:post' %}">Posts</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </footer>
    </div>
</body>

</html>

lostpets/lostpets_web/templates/home.html
{% extends 'base.html' %}

{% block title %}
LOST PETS - Inicio
{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row mb-4">
        <!-- Card 1: Imagen a la derecha -->
        <div class="col-md-12">
            <div class="card mb-3 border border-0">
                <div class="row g-3">
                    <div class="col-md-8 d-flex align-items-center">
                        <div class="card-body">
                            <h2 class="card-title">Encontramos a tu mascota</h2>
                            <p class="card-text">Sabemos lo importante que es tu mascota para ti. Nuestra comunidad
                                está aquí para ayudarte a reencontrarte con ella. Publica una alerta y revisa las
                                publicaciones de animales encontrados.</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <img src="https://cdn.aarp.net/content/dam/aarpe/es/home/hogar-familia/casa-jardin/info-2019/compartir-con-mascota-beneficios-para-salud/_jcr_content/root/container_main/container_body_main/container_body1/container_body_cf/container_image/articlecontentfragment/cfimage.coreimg.50.932.jpeg/content/dam/aarp/health/healthy-living/2019/03/1140-woman-and-dog-esp.jpg"
                            class="img-fluid rounded-end" style="width: 100%; height: 500px; object-fit: cover;"
                            alt="Mascota encontrada">
                    </div>
                </div>
            </div>
        </div>

        <span class="my-3"></span>

        <!-- Card 2: Imagen a la izquierda -->
        <div class="col-md-12">
            <div class="card mb-3 border border-0">
                <div class="row g-3">
                    <div class="col-md-4">
                        <img src="https://www.fundacionfass.org/wp-content/uploads/2022/10/Beneficios-de-las-mascotas-en-las-personas-mayores-2048x1365.jpg"
                            class="img-fluid rounded-start" style="width: 100%; height: 500px; object-fit: cover;"
                            alt="Mascota perdida">
                    </div>
                    <div class="col-md-8 d-flex align-items-center">
                        <div class="card-body">
                            <h2 class="card-title">Ayuda a encontrar a una mascota</h2>
                            <p class="card-text">Si has visto una mascota perdida, publica una foto y su ubicación.
                                Juntos podemos ayudar a reunir a las mascotas con sus familias.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

lostpets/lostpets_web/templates/login.html
{% extends 'base.html' %}

{% block title %}
LOST PETS - Login
{% endblock %}

{% block content %}
<div class="text-center my-5">
    <form method="POST" class="col-md-12">
        {% csrf_token %}
        <table class="mx-auto w-auto text-start">
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary mt-3">Ingresar Uusuario</button>
    </form>
</div>
{% endblock %}

lostpets/lostpets_web/templates/petdetail.html
{% extends 'base.html' %}

{% block title %}
LOST PETS - {{ pet.name }}
{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row mb-4">
        <!-- Card 1: Imagen a la derecha -->
        <div class="col-md-12">
            <div class="card mb-3 border border-0">
                <div class="row g-0">
                    <div class="col-md-8 d-flex align-items-center">
                        <div class="card-body">
                            <h2 class="card-title" style="font-size: 65px;">{{ pet.name }}</h2>
                            <p class="card-text">{{ pet.content }}</p>
                            <p class="list-group-item">Raza: {{ pet.race }}</p>
                            <p class="list-group-item">Fecha de publicación: {{ pet.published_date }}</p>
                            <p class="list-group-item text-capitalize">Dueño/a: {{ pet.owner}}</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <img src="{{ pet.image.url }}" class="img-fluid rounded-end"
                            style="width: 100%; height: 500px; object-fit: cover;" alt="Mascota encontrada">
                    </div>
                </div>
            </div>
        </div>

        <span class="my-3"></span>

    </div>
    {% endblock %}

lostpets/lostpets_web/templates/pets.html
{% extends 'base.html' %}

{% block title %}
LOST PETS - Pets
{% endblock %}

{% block content %}
<div class="container my-5">
    <h1 class="text-center">Mascotas perdidas</h1>
    <br>

    {% if pets %}
    <div class="row">
        {% for pet in pets %}
        <div class="col-md-4 mb-4">
            <div class="card" style="width: 100%;">
                <img src="{{ pet.image.url }}" class="card-img-top" alt="{{ pet.name }}"
                    style="height: 300px; object-fit: cover;">
                <div class="card-body">
                    <h5 class="card-title">{{ pet.name }}</h5>
                    <p class="card-text">{{ pet.content|slice:":40" }}{% if pet.content|length > 40 %}...{% endif %}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ pet.published_date }}</li>
                    <li class="list-group-item">Dueño: {{ pet.owner }}</li>
                </ul>
                <div class="card-body">
                    <a href="{% url 'lostpets_web:petdetail' pk=pet.pk %}" class="card-link">Ver más</a>
                    {% if request.user == pet.owner or request.user.is_staff %}
                    <a href="{% url 'lostpets_web:pet_update' pk=pet.pk %}" class="card-link">Editar</a>
                    <a class="card-link" style="cursor: pointer;" data-bs-toggle="modal"
                        data-bs-target="#avatarDeleteModal{{ pet.pk }}">Eliminar</a>
                    {% endif %}
                </div>
            </div>
        </div>

        {% if request.user == pet.owner or request.user.is_staff %}
        <div class="modal fade" id="avatarDeleteModal{{ pet.pk }}" tabindex="-1"
            aria-labelledby="avatarDeleteModal{{ pet.pk }}" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="avatarDeleteModal{{ pet.pk }}">
                            ¿Estás seguro de que deseas eliminar a "{{ pet.name }}"?
                        </h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">

                        <!-- Aquí va el formulario con el método POST -->
                        <form method="POST" action="{% url 'lostpets_web:pet_delete' pk=pet.pk %}">
                            {% csrf_token %}
                            <div class="modal-footer">
                                <button type="button" class="btn btn-warning" data-bs-dismiss="modal">No, Salir</button>
                                <button type="submit" class="btn btn-danger">Si, Eliminar</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% else %}
    <p class="text-center">No hay mascotas perdidas en este momento.</p>
    {% endif %}

</div>

{% endblock %}

lostpets/lostpets_web/templates/register.html
{% extends 'base.html' %}

{% block title %}
LOST PETS - Register
{% endblock %}

{% block content %}
<div class="text-center my-5">
    <form action="{% url 'lostpets_web:register' %}" method="post" class="col-md-12">
        {% csrf_token %}
        <table class="mx-auto w-auto text-start">
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Registrar Usuario Uusuario</button>
    </form>
</div>
{% endblock %}